### ISSUE TITLE
Reveal Modal - Body class

### ISSUE THREAD

**Issue by valentinchevalier** [circlingthesun/angular-foundation-6#10]
Hi,

The body has no class when a reveal-modal is append except when it's display on small screen.

Is it possible to add 'is-reveal-open' on body even on normal screen?

Thanks.

**Comment by circlingthesun** [comment]
Hey @valentinchevalier,

The 'is-reveal-open' class was originally applied to modals that fit the viewport. The problem is that dynamic content in a modal might make it grow after opening and overflow the viewpoint. If the 'is-reveal-open' class is present on the body when this happens, the user is unable to scroll the page in order to see the rest of the modal content.

Until this issue can be fixed, adding 'is-reveal-open' to all windows will cause more problems than it solves.

I'd be open to a PR that always adds 'is-reveal-open' as setting.

**Comment by circlingthesun** [comment]
@valentinchevalier, I did a refactor on the modal. The 'is-reveal-open' will always be added now.
