### ISSUE TITLE
Timeline on switch to angular 1.6x

### ISSUE THREAD

**Issue by DanielReid** [circlingthesun/angular-foundation-6#64]
Hi,

We'd like to add code to tooltip and dropdown components to close them on state transitions from the ui-router. However, angular made a breaking change in this system in the upgrade to 1.6 (which we use). so we'd like to know if/when this project plans to move to 1.6 so that we have a timeline for cleaning up and submitting a PR for that code.

**Comment by circlingthesun** [comment]
Hi Daniel. I can't think of a reason why it wouldn't work with angular 1.6. I use angular-foundation-6 with angular 1.6 in production. I had a look at your PR. It appears that it failed because of Github rate limiting. This has been an ongoing problem that I've not gotten around to. I'll try have a look at your PR later today.

**Comment by DanielReid** [comment]
Hi, 

Sorry, I had a brainfart and confused angular-ui-router with core angular. They're the ones who changed their state transition framework. We should be able to handle closing tooltips/dropdown on state transition with the event hook we added in the PR anyway. We've tried switching to 1.6.6 and everything is working fine indeed.
